#include "machines.hpp"

std::string e_machines_to_string(int64_t value)
{
  switch(value) {
    case 0:
      return "EM_NONE";
    case 1:
      return "EM_M32";
    case 2:
      return "EM_SPARC";
    case 3:
      return "EM_386";
    case 4:
      return "EM_68K";
    case 5:
      return "EM_88K";
    case 6:
      return "EM_IAMCU";
    case 7:
      return "EM_860";
    case 8:
      return "EM_MIPS";
    case 9:
      return "EM_S370";
    case 10:
      return "EM_MIPS_RS3_LE";
    case 11:
      return "e_machines_reserved_11";
    case 12:
      return "e_machines_reserved_12";
    case 13:
      return "e_machines_reserved_13";
    case 14:
      return "e_machines_reserved_14";
    case 15:
      return "EM_PARISC";
    case 16:
      return "e_machines_reserved_0";
    case 17:
      return "EM_VPP500";
    case 18:
      return "EM_SPARC32PLUS";
    case 19:
      return "EM_960";
    case 20:
      return "EM_PPC";
    case 21:
      return "EM_PPC64";
    case 22:
      return "EM_S390";
    case 23:
      return "EM_SPU";
    case 24:
      return "e_machines_reserved_24";
    case 25:
      return "e_machines_reserved_25";
    case 26:
      return "e_machines_reserved_26";
    case 27:
      return "e_machines_reserved_27";
    case 28:
      return "e_machines_reserved_28";
    case 29:
      return "e_machines_reserved_29";
    case 30:
      return "e_machines_reserved_30";
    case 31:
      return "e_machines_reserved_31";
    case 32:
      return "e_machines_reserved_32";
    case 33:
      return "e_machines_reserved_33";
    case 34:
      return "e_machines_reserved_34";
    case 35:
      return "e_machines_reserved_35";
    case 36:
      return "EM_V800";
    case 37:
      return "EM_FR20";
    case 38:
      return "EM_RH32";
    case 39:
      return "EM_RCE";
    case 40:
      return "EM_ARM";
    case 41:
      return "EM_ALPHA";
    case 42:
      return "EM_SH";
    case 43:
      return "EM_SPARCV9";
    case 44:
      return "EM_TRICORE";
    case 45:
      return "EM_ARC";
    case 46:
      return "EM_H8_300";
    case 47:
      return "EM_H8_300H";
    case 48:
      return "EM_H8S";
    case 49:
      return "EM_H8_500";
    case 50:
      return "EM_IA_64";
    case 51:
      return "EM_MIPS_X";
    case 52:
      return "EM_COLDFIRE";
    case 53:
      return "EM_68HC12";
    case 54:
      return "EM_MMA";
    case 55:
      return "EM_PCP";
    case 56:
      return "EM_NCPU";
    case 57:
      return "EM_NDR1";
    case 58:
      return "EM_STARCORE";
    case 59:
      return "EM_ME16";
    case 60:
      return "EM_ST100";
    case 61:
      return "EM_TINYJ";
    case 62:
      return "EM_X86_64";
    case 63:
      return "EM_PDSP";
    case 64:
      return "EM_PDP10";
    case 65:
      return "EM_PDP11";
    case 66:
      return "EM_FX66";
    case 67:
      return "EM_ST9PLUS";
    case 68:
      return "EM_ST7";
    case 69:
      return "EM_68HC16";
    case 70:
      return "EM_68HC11";
    case 71:
      return "EM_68HC08";
    case 72:
      return "EM_68HC05";
    case 73:
      return "EM_SVX";
    case 74:
      return "EM_ST19";
    case 75:
      return "EM_VAX";
    case 76:
      return "EM_CRIS";
    case 77:
      return "EM_JAVELIN";
    case 78:
      return "EM_FIREPATH";
    case 79:
      return "EM_ZSP";
    case 80:
      return "EM_MMIX";
    case 81:
      return "EM_HUANY";
    case 82:
      return "EM_PRISM";
    case 83:
      return "EM_AVR";
    case 84:
      return "EM_FR30";
    case 85:
      return "EM_D10V";
    case 86:
      return "EM_D30V";
    case 87:
      return "EM_V850";
    case 88:
      return "EM_M32R";
    case 89:
      return "EM_MN10300";
    case 90:
      return "EM_MN10200";
    case 91:
      return "EM_PJ";
    case 92:
      return "EM_OPENRISC";
    case 93:
      return "EM_ARC_COMPACT";
    case 94:
      return "EM_XTENSA";
    case 95:
      return "EM_VIDEOCORE";
    case 96:
      return "EM_TMM_GPP";
    case 97:
      return "EM_NS32K";
    case 98:
      return "EM_TPC";
    case 99:
      return "EM_SNP1K";
    case 100:
      return "EM_ST200";
    case 101:
      return "EM_IP2K";
    case 102:
      return "EM_MAX";
    case 103:
      return "EM_CR";
    case 104:
      return "EM_F2MC16";
    case 105:
      return "EM_MSP430";
    case 106:
      return "EM_BLACKFIN";
    case 107:
      return "EM_SE_C33";
    case 108:
      return "EM_SEP";
    case 109:
      return "EM_ARCA";
    case 110:
      return "EM_UNICORE";
    case 111:
      return "EM_EXCESS";
    case 112:
      return "EM_DXP";
    case 113:
      return "EM_ALTERA_NIOS2";
    case 114:
      return "EM_CRX";
    case 115:
      return "EM_XGATE";
    case 116:
      return "EM_C166";
    case 117:
      return "EM_M16C";
    case 118:
      return "EM_DSPIC30F";
    case 119:
      return "EM_CE";
    case 120:
      return "EM_M32C";
    case 121:
      return "e_machines_reserved_121";
    case 122:
      return "e_machines_reserved_122";
    case 123:
      return "e_machines_reserved_123";
    case 124:
      return "e_machines_reserved_124";
    case 125:
      return "e_machines_reserved_125";
    case 126:
      return "e_machines_reserved_126";
    case 127:
      return "e_machines_reserved_127";
    case 128:
      return "e_machines_reserved_128";
    case 129:
      return "e_machines_reserved_129";
    case 130:
      return "e_machines_reserved_130";
    case 131:
      return "EM_TSK3000";
    case 132:
      return "EM_RS08";
    case 133:
      return "EM_SHARC";
    case 134:
      return "EM_ECOG2";
    case 135:
      return "EM_SCORE7";
    case 136:
      return "EM_DSP24";
    case 137:
      return "EM_VIDEOCORE3";
    case 138:
      return "EM_LATTICEMICO32";
    case 139:
      return "EM_SE_C17";
    case 140:
      return "EM_TI_C6000";
    case 141:
      return "EM_TI_C2000";
    case 142:
      return "EM_TI_C5500";
    case 143:
      return "EM_TI_ARP32";
    case 144:
      return "EM_TI_PRU";
    case 145:
      return "e_machines_reserved_145";
    case 146:
      return "e_machines_reserved_146";
    case 147:
      return "e_machines_reserved_147";
    case 148:
      return "e_machines_reserved_148";
    case 149:
      return "e_machines_reserved_149";
    case 150:
      return "e_machines_reserved_150";
    case 151:
      return "e_machines_reserved_151";
    case 152:
      return "e_machines_reserved_152";
    case 153:
      return "e_machines_reserved_153";
    case 154:
      return "e_machines_reserved_154";
    case 155:
      return "e_machines_reserved_155";
    case 156:
      return "e_machines_reserved_156";
    case 157:
      return "e_machines_reserved_157";
    case 158:
      return "e_machines_reserved_158";
    case 159:
      return "e_machines_reserved_159";
    case 160:
      return "EM_MMDSP_PLUS";
    case 161:
      return "EM_CYPRESS_M8C";
    case 162:
      return "EM_R32C";
    case 163:
      return "EM_TRIMEDIA";
    case 164:
      return "EM_QDSP6";
    case 165:
      return "EM_8051";
    case 166:
      return "EM_STXP7X";
    case 167:
      return "EM_NDS32";
    case 168:
      return "EM_ECOG1";
    case 169:
      return "EM_MAXQ30";
    case 170:
      return "EM_XIMO16";
    case 171:
      return "EM_MANIK";
    case 172:
      return "EM_CRAYNV2";
    case 173:
      return "EM_RX";
    case 174:
      return "EM_METAG";
    case 175:
      return "EM_MCST_ELBRUS";
    case 176:
      return "EM_ECOG16";
    case 177:
      return "EM_CR16";
    case 178:
      return "EM_ETPU";
    case 179:
      return "EM_SLE9X";
    case 180:
      return "EM_L10M";
    case 181:
      return "EM_K10M";
    case 182:
      return "e_machines_reserved_1";
    case 183:
      return "EM_AARCH64";
    case 184:
      return "e_machines_reserved_2";
    case 185:
      return "EM_AVR32";
    case 186:
      return "EM_STM8";
    case 187:
      return "EM_TILE64";
    case 188:
      return "EM_TILEPRO";
    case 189:
      return "EM_MICROBLAZE";
    case 190:
      return "EM_CUDA";
    case 191:
      return "EM_TILEGX";
    case 192:
      return "EM_CLOUDSHIELD";
    case 193:
      return "EM_COREA_1ST";
    case 194:
      return "EM_COREA_2ND";
    case 195:
      return "EM_ARC_COMPACT2";
    case 196:
      return "EM_OPEN8";
    case 197:
      return "EM_RL78";
    case 198:
      return "EM_VIDEOCORE5";
    case 199:
      return "EM_78KOR";
    case 200:
      return "EM_56800EX";
    case 201:
      return "EM_BA1";
    case 202:
      return "EM_BA2";
    case 203:
      return "EM_XCORE";
    case 204:
      return "EM_MCHP_PIC";
    case 205:
      return "EM_INTEL205";
    case 206:
      return "EM_INTEL206";
    case 207:
      return "EM_INTEL207";
    case 208:
      return "EM_INTEL208";
    case 209:
      return "EM_INTEL209";
    case 210:
      return "EM_KM32";
    case 211:
      return "EM_KMX32";
    case 212:
      return "EM_KMX16";
    case 213:
      return "EM_KMX8";
    case 214:
      return "EM_KVARC";
    case 215:
      return "EM_CDP";
    case 216:
      return "EM_COGE";
    case 217:
      return "EM_COOL";
    case 218:
      return "EM_NORC";
    case 219:
      return "EM_CSR_KALIMBA";
    case 220:
      return "EM_Z80";
    case 221:
      return "EM_VISIUM";
    case 222:
      return "EM_FT32";
    case 223:
      return "EM_MOXIE";
    case 224:
      return "EM_AMDGPU";
    case 225:
      return "e_machines_reserved_225";
    case 226:
      return "e_machines_reserved_226";
    case 227:
      return "e_machines_reserved_227";
    case 228:
      return "e_machines_reserved_228";
    case 229:
      return "e_machines_reserved_229";
    case 230:
      return "e_machines_reserved_230";
    case 231:
      return "e_machines_reserved_231";
    case 232:
      return "e_machines_reserved_232";
    case 233:
      return "e_machines_reserved_233";
    case 234:
      return "e_machines_reserved_234";
    case 235:
      return "e_machines_reserved_235";
    case 236:
      return "e_machines_reserved_236";
    case 237:
      return "e_machines_reserved_237";
    case 238:
      return "e_machines_reserved_238";
    case 239:
      return "e_machines_reserved_239";
    case 240:
      return "e_machines_reserved_240";
    case 241:
      return "e_machines_reserved_241";
    case 242:
      return "e_machines_reserved_242";
    case 243:
      return "EM_RISCV";
    default:
      return "unknown";
  }
}

