#ifndef E_SECTION_TYPES_HPP
#define E_SECTION_TYPES_HPP

// This file is automatically generated, do not edit.

#include <string>

enum e_section_types {
    SHT_NULL                                = 0,         // Description not available
    SHT_PROGBITS                            = 1,         // Description not available
    SHT_SYMTAB                              = 2,         // Description not available
    SHT_STRTAB                              = 3,         // Description not available
    SHT_RELA                                = 4,         // Description not available
    SHT_HASH                                = 5,         // Description not available
    SHT_DYNAMIC                             = 6,         // Description not available
    SHT_NOTE                                = 7,         // Description not available
    SHT_NOBITS                              = 8,         // Description not available
    SHT_REL                                 = 9,         // Description not available
    SHT_SHLIB                               = 10,        // Description not available
    SHT_DYNSYM                              = 11,        // Description not available
    SHT_INIT_ARRAY                          = 14,        // Description not available
    SHT_FINI_ARRAY                          = 15,        // Description not available
    SHT_PREINIT_ARRAY                       = 16,        // Description not available
    SHT_GROUP                               = 17,        // Description not available
    SHT_SYMTAB_SHNDX                        = 18,        // Description not available
    SHT_LOOS                                = 0x60000000, // Description not available
    SHT_HIOS                                = 0x6FFFFFFF, // Description not available
    SHT_LOPROC                              = 0x70000000, // Description not available
    SHT_HIPROC                              = 0x7FFFFFFF, // Description not available
    SHT_LOUSER                              = 0x80000000, // Description not available
    SHT_HIUSER                              = 0xFFFFFFFF // Description not available
};

std::string e_section_types_to_string(int64_t value);



#endif // end of E_SECTION_TYPES_HPP
